/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type Organizationget struct {
	AccountsReceivable               string      `json:"accountsReceivable,omitempty"`
	Created                          string      `json:"created,omitempty"`
	DisplayName                      string      `json:"displayName,omitempty"`
	Entitlement                      interface{} `json:"entitlement,omitempty"`
	HasCreditCard                    bool        `json:"hasCreditCard,omitempty"`
	HasStripeCustomerId              bool        `json:"hasStripeCustomerId,omitempty"`
	Id                               string      `json:"_id,omitempty"`
	LastEstimateCalculationTimeStamp string      `json:"lastEstimateCalculationTimeStamp,omitempty"`
	LastSfdcSyncStatus               interface{} `json:"lastSfdcSyncStatus,omitempty"`
	LogoUrl                          string      `json:"logoUrl,omitempty"`
	Provider                         string      `json:"provider,omitempty"`
	Settings                         interface{} `json:"settings,omitempty"`
	TotalBillingEstimate             int32       `json:"totalBillingEstimate,omitempty"`
}

