/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type Sshkeylist struct {

	// The ID of the SSH key.
	Id string `json:"_id,omitempty"`

	// The date the SSH key was created.
	CreateDate string `json:"create_date,omitempty"`

	// The name of the SSH key.
	Name string `json:"name,omitempty"`

	// The Public SSH key.
	PublicKey string `json:"public_key,omitempty"`
}
