/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type SystemuserreturnAddresses struct {

	Country string `json:"country,omitempty"`

	ExtendedAddress string `json:"extendedAddress,omitempty"`

	Id string `json:"id,omitempty"`

	Locality string `json:"locality,omitempty"`

	PoBox string `json:"poBox,omitempty"`

	PostalCode string `json:"postalCode,omitempty"`

	Region string `json:"region,omitempty"`

	StreetAddress string `json:"streetAddress,omitempty"`

	Type_ string `json:"type,omitempty"`
}
