/*
 * JumpCloud APIs
 *
 * V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type Systemuserreturn struct {

	Email string `json:"email,omitempty"`

	Username string `json:"username,omitempty"`

	AllowPublicKey bool `json:"allow_public_key,omitempty"`

	PublicKey string `json:"public_key,omitempty"`

	SshKeys []string `json:"ssh_keys,omitempty"`

	Sudo bool `json:"sudo,omitempty"`

	EnableManagedUid bool `json:"enable_managed_uid,omitempty"`

	UnixUid int32 `json:"unix_uid,omitempty"`

	UnixGuid int32 `json:"unix_guid,omitempty"`

	Activated bool `json:"activated,omitempty"`

	Tags []string `json:"tags,omitempty"`

	PasswordExpired bool `json:"password_expired,omitempty"`

	AccountLocked bool `json:"account_locked,omitempty"`

	PasswordlessSudo bool `json:"passwordless_sudo,omitempty"`

	ExternallyManaged bool `json:"externally_managed,omitempty"`

	ExternalDn string `json:"external_dn,omitempty"`

	ExternalSourceType string `json:"external_source_type,omitempty"`

	Firstname string `json:"firstname,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	LdapBindingUser bool `json:"ldap_binding_user,omitempty"`

	EnableUserPortalMultifactor bool `json:"enable_user_portal_multifactor,omitempty"`

	TotpEnabled bool `json:"totp_enabled,omitempty"`

	Attributes []interface{} `json:"attributes,omitempty"`

	Created string `json:"created,omitempty"`

	SambaServiceUser bool `json:"samba_service_user,omitempty"`

	Id string `json:"id,omitempty"`

	Organization string `json:"organization,omitempty"`

	Addresses []string `json:"addresses,omitempty"`

	JobTitle string `json:"jobTitle,omitempty"`

	Department string `json:"department,omitempty"`

	PhoneNumbers []string `json:"phoneNumbers,omitempty"`

	Relationships []interface{} `json:"relationships,omitempty"`

	BadLoginAttempts int32 `json:"badLoginAttempts,omitempty"`

	PasswordNeverExpires bool `json:"password_never_expires,omitempty"`
}
