/*
 * JumpCloud APIs
 *
 * V1 & V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type Tagslist struct {

	// The total number of tags.
	TotalCount int32 `json:"totalCount,omitempty"`

	// The list of tags.
	Results []Tag `json:"results,omitempty"`
}
