/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type Administrator struct {

	Id string `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	Firstname string `json:"firstname,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	EnableMultiFactor bool `json:"enableMultiFactor,omitempty"`

	Registered bool `json:"registered,omitempty"`
}
