/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type AppleMdm struct {

	// The push topic assigned to this enrollment by Apple after uploading the Signed CSR plist.
	ApnsPushTopic string `json:"apnsPushTopic,omitempty"`

	// ObjectId uniquely identifying an MDM Enrollment,
	Id string `json:"id"`

	// A friendly name to identify this enrollment.  Not required to be unique.
	Name string `json:"name,omitempty"`
}
