/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type BulkUserUpdate struct {

	// Object ID of the systemuser being updated
	Id string `json:"id,omitempty"`

	// Map of attributes to be updated. If a passed attribute is not a top-level `systemuser` attributes, it will be added to custom attributes.
	Attributes []interface{} `json:"attributes,omitempty"`
}
