/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2
// Office365BuiltinTranslation : Built-in translations for Office 365 (Microsoft Graph) export: * `user_street_address` - Translate `streetAddress` field of JumpCloud user address of type `work` to `city` field of Microsoft Graph user * `user_city` - Translate `locality` field of JumpCloud user address of type `work` to `city` field of Microsoft Graph user * `user_state` - Translate `region` field of JumpCloud user address of type `work` to `state` field of Microsoft Graph `user` * `user_country` - Translate `country` field of JumpCloud user address of type `work` to `country` field of Microsoft Graph `user` * `user_postal_code` - Translate `postalCode` field of JumpCloud user address of type `work` to `postalCode` field of Microsoft Graph `user` * `user_business_phones` - Translate `number` field of first JumpCloud user `phoneNumber` of type `work` to `businessPhones` field of Microsoft Graph `user` * `user_mobile_phone` - Translate `number` field of first JumpCloud user `phoneNumber` of type `mobile` to `mobilePhone` field of Microsoft Graph `user` * `user_department` - Translate `department` field of JumpCloud user to `department` field of Microsoft Graph `user` * `user_job_title` - Translate `jobTitle` field of JumpCloud user to `jobTitle` field of Microsoft Graph `user` * `user_office_location` - Translate `location` field of JumpCloud user to `officeLocation` field of Microsoft Graph `user`
type Office365BuiltinTranslation string

// List of Office365BuiltinTranslation
const (
	STREET_ADDRESS Office365BuiltinTranslation = "user_street_address"
	CITY Office365BuiltinTranslation = "user_city"
	STATE Office365BuiltinTranslation = "user_state"
	COUNTRY Office365BuiltinTranslation = "user_country"
	POSTAL_CODE Office365BuiltinTranslation = "user_postal_code"
	BUSINESS_PHONES Office365BuiltinTranslation = "user_business_phones"
	MOBILE_PHONE Office365BuiltinTranslation = "user_mobile_phone"
	DEPARTMENT Office365BuiltinTranslation = "user_department"
	JOB_TITLE Office365BuiltinTranslation = "user_job_title"
	OFFICE_LOCATION Office365BuiltinTranslation = "user_office_location"
)
