/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsSipConfig struct {

	CollectionTime string `json:"collection_time,omitempty"`

	ConfigFlag string `json:"config_flag,omitempty"`

	Enabled int32 `json:"enabled,omitempty"`

	EnabledNvram int32 `json:"enabled_nvram,omitempty"`

	SystemId string `json:"system_id,omitempty"`
}
