/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsPrograms struct {

	CollectionTime string `json:"collection_time,omitempty"`

	IdentifyingNumber string `json:"identifying_number,omitempty"`

	InstallDate string `json:"install_date,omitempty"`

	InstallLocation string `json:"install_location,omitempty"`

	InstallSource string `json:"install_source,omitempty"`

	Language string `json:"language,omitempty"`

	Name string `json:"name,omitempty"`

	Publisher string `json:"publisher,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	UninstallString string `json:"uninstall_string,omitempty"`

	Version string `json:"version,omitempty"`
}
