/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsUsers struct {

	CollectionTime string `json:"collection_time,omitempty"`

	Description string `json:"description,omitempty"`

	Directory string `json:"directory,omitempty"`

	Gid string `json:"gid,omitempty"`

	GidSigned string `json:"gid_signed,omitempty"`

	Shell string `json:"shell,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Uid string `json:"uid,omitempty"`

	UidSigned string `json:"uid_signed,omitempty"`

	Username string `json:"username,omitempty"`

	Uuid string `json:"uuid,omitempty"`
}
