/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsSafariExtensions struct {

	Author string `json:"author,omitempty"`

	CollectionTime string `json:"collection_time,omitempty"`

	Description string `json:"description,omitempty"`

	DeveloperId string `json:"developer_id,omitempty"`

	Identifier string `json:"identifier,omitempty"`

	Name string `json:"name,omitempty"`

	Path string `json:"path,omitempty"`

	Sdk string `json:"sdk,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	Uid string `json:"uid,omitempty"`

	UpdateUrl string `json:"update_url,omitempty"`

	Version string `json:"version,omitempty"`
}
