/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsBrowserPlugins struct {

	Uid string `json:"uid,omitempty"`

	Name string `json:"name,omitempty"`

	Identifier string `json:"identifier,omitempty"`

	Version string `json:"version,omitempty"`

	Sdk string `json:"sdk,omitempty"`

	Description string `json:"description,omitempty"`

	DevelopmentRegion string `json:"development_region,omitempty"`

	Native int32 `json:"native,omitempty"`

	Path string `json:"path,omitempty"`

	Disabled int32 `json:"disabled,omitempty"`

	CollectionTime string `json:"collection_time,omitempty"`

	SystemId string `json:"system_id,omitempty"`
}
