/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsFirefoxAddons struct {

	Uid string `json:"uid,omitempty"`

	Name string `json:"name,omitempty"`

	Identifier string `json:"identifier,omitempty"`

	Creator string `json:"creator,omitempty"`

	Type_ string `json:"type,omitempty"`

	Version string `json:"version,omitempty"`

	Description string `json:"description,omitempty"`

	SourceUrl string `json:"source_url,omitempty"`

	Visible int32 `json:"visible,omitempty"`

	Active int32 `json:"active,omitempty"`

	Disabled int32 `json:"disabled,omitempty"`

	Autoupdate int32 `json:"autoupdate,omitempty"`

	Location string `json:"location,omitempty"`

	Path string `json:"path,omitempty"`

	JcCollectionTime string `json:"jc_collection_time,omitempty"`

	JcSystemId string `json:"jc_system_id,omitempty"`

	JcOrganizationId string `json:"jc_organization_id,omitempty"`
}
