/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsCrashes struct {

	Type_ string `json:"type,omitempty"`

	Pid string `json:"pid,omitempty"`

	Path string `json:"path,omitempty"`

	CrashPath string `json:"crash_path,omitempty"`

	Identifier string `json:"identifier,omitempty"`

	Version string `json:"version,omitempty"`

	Parent string `json:"parent,omitempty"`

	Responsible string `json:"responsible,omitempty"`

	Uid int32 `json:"uid,omitempty"`

	Datetime string `json:"datetime,omitempty"`

	CrashedThread string `json:"crashed_thread,omitempty"`

	StackTrace string `json:"stack_trace,omitempty"`

	ExceptionType string `json:"exception_type,omitempty"`

	ExceptionCodes string `json:"exception_codes,omitempty"`

	ExceptionNotes string `json:"exception_notes,omitempty"`

	Registers string `json:"registers,omitempty"`
}
