/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsUsbDevices struct {

	Class string `json:"class,omitempty"`

	CollectionTime string `json:"collection_time,omitempty"`

	Model string `json:"model,omitempty"`

	ModelId string `json:"model_id,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Removable int32 `json:"removable,omitempty"`

	Serial string `json:"serial,omitempty"`

	Subclass string `json:"subclass,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	UsbAddress int32 `json:"usb_address,omitempty"`

	UsbPort int32 `json:"usb_port,omitempty"`

	Vendor string `json:"vendor,omitempty"`

	VendorId string `json:"vendor_id,omitempty"`

	Version string `json:"version,omitempty"`
}
