/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemInsightsDiskInfo struct {

	CollectionTime string `json:"collection_time,omitempty"`

	Description string `json:"description,omitempty"`

	DiskIndex int32 `json:"disk_index,omitempty"`

	DiskSize string `json:"disk_size,omitempty"`

	HardwareModel string `json:"hardware_model,omitempty"`

	Id string `json:"id,omitempty"`

	Manufacturer string `json:"manufacturer,omitempty"`

	Name string `json:"name,omitempty"`

	Partitions int32 `json:"partitions,omitempty"`

	PnpDeviceId string `json:"pnp_device_id,omitempty"`

	Serial string `json:"serial,omitempty"`

	SystemId string `json:"system_id,omitempty"`

	Type_ string `json:"type,omitempty"`
}
