/*
 * JumpCloud APIs
 *
 * V1 & V2 versions of JumpCloud's API. The next version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings. The most recent version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type UserGroup struct {

	// ObjectId uniquely identifying a User Group.
	Id string `json:"id,omitempty"`

	// The type of the group.
	Type_ string `json:"type,omitempty"`

	// Display name of a User Group.
	Name string `json:"name,omitempty"`
}
