/*
 * JumpCloud APIs
 *
 *  JumpCloud's V2 API. This set of endpoints allows JumpCloud customers to manage objects, groupings and mappings and interact with the JumpCloud Graph.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v2

type SystemuserputpostAddresses struct {

	Type_ string `json:"type,omitempty"`

	PoBox string `json:"poBox,omitempty"`

	ExtendedAddress string `json:"extendedAddress,omitempty"`

	StreetAddress string `json:"streetAddress,omitempty"`

	Locality string `json:"locality,omitempty"`

	Region string `json:"region,omitempty"`

	PostalCode string `json:"postalCode,omitempty"`

	Country string `json:"country,omitempty"`
}
