/* 
 * JumpCloud APIs
 *
 * V1 and V2 versions of JumpCloud's API. The previous version of JumpCloud's API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package v1

type Commands struct {

	Name string `json:"name,omitempty"`

	// The command to execute on the server.
	Command string `json:"command"`

	// The ID of the JC managed user to run the command as.
	User string `json:"user"`

	// An array of system IDs to run the command on.
	Systems []string `json:"systems,omitempty"`

	// A crontab that consists of: [ (seconds) (minutes) (hours) (days of month) (months) (weekdays) ] or [ immediate ]. If you send this as an empty string, it will run immediately. 
	Schedule string `json:"schedule,omitempty"`

	// An array of file IDs to include with the command.
	Files []string `json:"files,omitempty"`

	// An array of tag IDs to run the command on.
	Tags []string `json:"tags,omitempty"`

	// The time in seconds to allow the command to run for.
	Timeout string `json:"timeout,omitempty"`
}
