/*
 * JumpCloud APIs
 *
 *  JumpCloud's V1 API. This set of endpoints allows JumpCloud customers to manage commands, systems, & system users.
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1

type SystemNetworkInterfaces struct {

	Address string `json:"address,omitempty"`

	Family string `json:"family,omitempty"`

	Internal bool `json:"internal,omitempty"`

	Name string `json:"name,omitempty"`
}
